name: Build
on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      #id-token: read
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        env:
          URL_PREFIX: ${{ github.ref_name }}
        run: mvn install -Dquarkus.container-image.push=true

      - name: Install kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl unzip
          curl -fsSLO https://github.com/int128/kubelogin/releases/download/v1.25.4/kubelogin_linux_amd64.zip
          unzip kubelogin_linux_amd64.zip kubelogin -d kubelogin
          mv kubelogin/kubelogin kubelogin/kubectl-oidc_login
          export PATH=$PATH:$(realpath kubelogin)
          mkdir ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          kubectl apply -f target/kubernetes/kubernetes.yml